@startuml
title
**__Secuencia de Turno de Colocacion__**
Con canje de tarjetas
endtitle
skinparam responseMessageBelowArrow true
skinparam monochrome true
skinparam style strictuml
hide footbox

actor Actor
participant colocacion as ":Colocacion"
participant juego as ":Juego"
participant jug as ":Jugador"
participant trj as ":Tarjeta"
participant Tarjeta

Actor ++
Actor -> colocacion ++: new Colocacion()
loop Para cada jugdor
    colocacion -> jug ++: actualizarFichas()
    jug ->jug ++: canjearTarjetas()

        jug -> Tarjeta ++: grupoCanjeable(tarjetas)
        jug <-- Tarjeta --: grupoCanjeable
        jug -> jug : tarjetas.remove(grupoCanjeable)
        jug -> juego : devolverTarjetas(grupoCanjeable)
        jug -> Tarjeta ++: cantidadFichasCanje(cantidadCanjes)
        return cantidadFichas
        jug --


        jug -> jug ++: fichasPorConquista()
        juego <- jug ++: fichasSegunContinentes(paises)
        juego --> jug : fichasSegunContinentes
        juego --
        jug --> jug --: fichasPorPaisesConquistados + fichasSegunContinentes

    note left: se actualiza la cantidad de fichas \n disponibles que tiene el jugador
end loop

jug--

colocacion -> : new AgregadorEjercitos()

colocacion --
@enduml
