@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide empty members

title **__TEG__**

class Juego{
	+ inicializar()
    + colocarFichasIniciales()
}
class Mapa{
    + repartirPaises(jugadores : ArrayList<Jugador>)
    + fichasSegunContinentes(paisesConquistados : Set<String>) : int 	
}

class Pais{
	- cantidadFichas :Int
	- continente :String
	- vecinos :Pais[]
}
class Jugador{
    + atacar(atacante:Pais,defensor:Pais,cantFichas:Int)
    + agregarFichas(cantFichas:Int)
    + ocupar(pais:Pais)
    + desocupar(pais:Pais)
    + turnoAtaque()
    + turnoColocacion()
}

Interface Objetivo<<Interface>>{
	+ gano(jugador:Jugador): bool
}

class Tarjeta{
    - tipo : String
    - nombrePais : String
    {static} + cantidadFichasCanje(canjesRealizados : int) : int
    {static} + grupoCanjeable(tarjetas : ArrayList<Tarjeta>) : ArrayList<Tarjeta>
    + activar()
    + desactivar()
}

class Batalla {

}

class Simbolo {
    + esIgualA(otroSimbolo : Simbolo) : bool
}

Pais .> Batalla
Batalla  "1" o- "2" Pais

Juego *- Mapa
Mapa *- "50" Pais

Juego *-- "2,6" Jugador

Jugador "1"--"*" Pais

Jugador -left> Objetivo
Tarjeta "0..5" --o "1" Jugador
Juego "1" *-l "50" Tarjeta: "\t"

Tarjeta -l> Simbolo

Mapa .l> Jugador

@enduml