@startuml
title Secuencia de obtención de Tarjeta
skinparam responseMessageBelowArrow true
skinparam monochrome true
skinparam style strictuml
hide footbox

actor Actor
participant jueg as ":Juego"
participant jug as ":Jugador"
participant pais as ":Pais"

Actor -> jueg ++: rondaAtaques()

loop Para cada jugador
    jueg -> jug ++: turnoAtaque()
    note right: cant = len(paises)
    loop Para cada ataque
        jug -> pais: atacar(defensor, 5)
        jug <-] : ocupar(defensor)
    end loop

    jug -> jueg ++: pedirTarjeta()
    note right: if len(paises) > cant
    jueg --> jug --: unaTarjeta
    deactivate jug

    jueg -> jug: turnoReagrupacion()
    note over jug
        Mover fichas entre paises vecinos
    end note
end loop

Actor -> jueg: rondaColocacion()
loop Para cada jugdor
    jueg -> jug: turnoColocacion()
    note over jug
        1) Loopear tus tarjetas, si podes canjear una
        de un pais que tenes lo haces
        2) Fijarte si podes canjear 3 tarjetas
        3) Agregar fichas nuevas, checkeando tu cantidad
        de paises y si tenes algun continente entero + 
        las del posible canje
    end note
end loop
@enduml
