@startuml
title Secuencia de obtención de Tarjeta
skinparam responseMessageBelowArrow true
skinparam monochrome true
skinparam style strictuml
hide footbox

actor Actor
participant jueg as ":Juego"
participant jug as ":Jugador"
participant pais as ":Pais"

Actor ++
Actor -> jueg ++: rondaAtaques()

loop Para cada jugador
    jueg -> jug ++: turnoAtaque()
    note right: cant = len(paises)
    loop Para cada ataque
        jug -> pais ++: atacar(defensor, cantFichas)
        jug <-] ++: ocupar(defensor)
        pais --
        jug --
    end loop

    jug -> jueg ++: pedirTarjeta()
    note right: if len(paises) > cant
    jueg --> jug --: unaTarjeta
    deactivate jug

    jueg -> jug ++: turnoReagrupacion()
    loop Para cada reagrupación
        jug -> pais ++: reagruparA(destinatario, cantFichas)
    end loop

end loop

@enduml
